export * from './types';
export * from './iam';
export * from './config/grades';
export * from './config/layerPolicies';
export * from './naming';
export * from './access';
export * from './metrics';
export * from './materialize';
export * from './modeling';
export * from './ddl';
export * from './specChat';
export * from './specIo';
export * from './modelVersion';
export * from './fieldLogic';
export * from './impact';
export * from './modelChat';
export * from './aiPrompts';
export * from './knowledge';
export * from './knowledgeIo';
// 嵌壳协议的消息契约（子应用 → 宿主的运行期菜单树）。两端共同 import，
// 改单边会编译期报错 —— 见该文件的说明。
export * from './embedNav';
