import {
  ApartmentOutlined,
  ApiOutlined,
  AppstoreOutlined,
  AuditOutlined,
  BlockOutlined,
  BookOutlined,
  ClusterOutlined,
  DashboardOutlined,
  DatabaseOutlined,
  InboxOutlined,
  MessageOutlined,
  PartitionOutlined,
  RobotOutlined,
  SafetyCertificateOutlined,
  ScheduleOutlined,
  ShopOutlined,
  SwapOutlined,
  TableOutlined,
  TagOutlined,
  ThunderboltOutlined,
  ExperimentOutlined,
} from '@ant-design/icons-vue';

export const navIcons: Record<string, object> = {
  DashboardOutlined,
  InboxOutlined,
  ApartmentOutlined,
  DatabaseOutlined,
  MessageOutlined,
  BookOutlined,
  RobotOutlined,
  ClusterOutlined,
  SafetyCertificateOutlined,
  ScheduleOutlined,
  AuditOutlined,
  PartitionOutlined,
  ThunderboltOutlined,
  AppstoreOutlined,
  BlockOutlined,
  ApiOutlined,
  ShopOutlined,
  SwapOutlined,
  TableOutlined,
  TagOutlined,
  ExperimentOutlined,
};
